    <!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>OBSIC</title>
        <link href="customer/css/animate.min.css" rel="stylesheet"> 
        <link href="customer/css/font-awesome.min.css" rel="stylesheet">
        <link href="customer/css/lightbox.css" rel="stylesheet">
        <link href="customer/css/main.css" rel="stylesheet">
        <link id="css-preset" href="customer/css/presets/preset1.css" rel="stylesheet">
        <link href="customer/css/responsive.css" rel="stylesheet">

        <!--[if lt IE 9]>
          <script src="js/html5shiv.js"></script>
          <script src="js/respond.min.js"></script>
        <![endif]-->

        <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
        <link rel="shortcut icon" href="images/favicon.ico">
    </head><!--/head-->

    <body>
        <div>
            <section id="contact">
                <div id="google-map" class="wow fadeIn" data-latitude="52.365629" data-longitude="4.871331" data-wow-duration="1000ms" data-wow-delay="400ms"></div>
                <div id="contact-us" class="parallax">
                    <div class="container">
                        <div class="row">
                            <div class="heading text-center col-sm-8 col-sm-offset-2 wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
                                <h2>Contactez nous</h2>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim ad minim veniam</p>
                            </div>
                        </div>
                        <div class="contact-form wow fadeIn" data-wow-duration="1000ms" data-wow-delay="600ms">
                            <div class="row">
                                <div class="col-sm-6">
                                    <form id="main-contact-form" name="contact-form" method="post" action="#">
                                        <div class="row  wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
                                            <div class="col-sm-6">
                                                <div class="form-group">
                                                    <input type="text" name="name" class="form-control" placeholder="Nom" required="required">
                                                </div>
                                            </div>
                                            <div class="col-sm-6">
                                                <div class="form-group">
                                                    <input type="email" name="email" class="form-control" placeholder="Adresse Email" required="required">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <input type="text" name="subject" class="form-control" placeholder="Objet" required="required">
                                        </div>
                                        <div class="form-group">
                                            <textarea name="message" id="message" class="form-control" rows="4" placeholder="Entrez votre message" required="required"></textarea>
                                        </div>                        
                                        <div class="form-group">
                                            <button type="submit" class="btn-submit">Envoyer</button>
                                        </div>
                                    </form>   
                                </div>
                                <div class="col-sm-6">
                                    <div class="contact-info wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
                                        <p>OBSIC est une entreprise dont l'activité principale est centrée sur la ventre des produits électriques, la prestation des services, conseils.</p>
                                        <ul class="address">
                                            <li><i class="glyphicon glyphicon-envelope"></i> <span> Adresse:</span> Maroua Artisanal </li>
                                            <li><i class="fa fa-phone"></i> <span> Téléphone:</span> +928 336 2000  </li>
                                            <li><i class="fa fa-envelope"></i> <span> Adresse Email:</span><a href="mailto:someone@yoursite.com"> support@oxygen.com</a></li>
                                            <li><i class="fa fa-globe"></i> <span> Site:</span> <a href="#">www.obsic.com</a></li>
                                        </ul>
                                    </div>                            
                                </div>
                            </div>
                        </div>
                    </div>
                </div>        
            </section><!--/#contact-->
            <footer id="footer">
                <div class="footer-top wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
                    <div class="container text-center">
                        <div class="footer-logo">
                            <a href="index.html"><img class="img-responsive" src="customer/images/logo.png" alt=""></a>
                        </div>
                        <div class="social-icons">
                            <ul>
                                <li><a class="envelope" href="#"><i class="glyphicon glyphicon-envelope"></i></a></li>
                                <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li> 
                                <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
                                <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a class="tumblr" href="#"><i class="fa fa-tumblr-square"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </footer>


            <script type="text/javascript" src="customer/js/jquery.js"></script>
            <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
            <script type="text/javascript" src="customer/js/wow.min.js"></script>
            <script type="text/javascript" src="customer/js/mousescroll.js"></script>
            <script type="text/javascript" src="customer/js/smoothscroll.js"></script>
            <script type="text/javascript" src="customer/js/jquery.countTo.js"></script>
            <script type="text/javascript" src="customer/js/lightbox.min.js"></script>
            <script type="text/javascript" src="customer/js/main.js"></script>
        </div>
    </body>
</html>