<?php
echo $this->headLink()
        ->prependStylesheet($this->basePath('customer/footer/css/footer.css'))
?>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
<link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">
<div style="opacity: 0.8">  
    <!-- The content of your page would go here. -->
    <div class="footer-distributed" style="margin: 0; padding: 55px">
        <div class="footer-left">
            <h3>SASSIRE<span>-IT</span></h3>
            <p class="footer-links">
                <a href="#">Services</a>                    ·                   ·
                <a href="#">R&eacute;alisations</a>                    ·
                <a href="#">Modèles</a>                    ·                   ·
            </p>            
        </div>

        <div class="footer-center">
            <h3>Contactez-nous</h3>
            <div class="">
                <p> <a href="#" data-placement="top"
                       title="B.P. 2861 Yaound&eacute; Messa-Cameroun"><span class="glyphicon glyphicon-home">&nbsp;&nbsp;B.P.
                            2861 Yaound&eacute Messa-Cameroun;</span></a></p>
            </div>
            <div>
                <p><a href="provincialcam@yahoo.fr" data-placement="top"
                      title="provincialcam@yahoo.fr"><span class="glyphicon glyphicon-envelope">&nbsp;&nbsp;provincialcam@yahoo.fr</span></a></p>
            </div>
            <div>
                <p><a href="#" data-placement="top"
                      title="T&eacute;l&eacute;phone"><span class="glyphicon glyphicon-phone">&nbsp;&nbsp;Tél.fixe (237) 243 59 52 46</span></a></p>
            </div>
            <div>
                <p><a href="#" data-placement="top"
                      title="T&eacute;l&eacute;phone mobile "><span class="glyphicon glyphicon-phone-alt">&nbsp;&nbsp;243 566 159</span>
                    </a></p>
            </div>
        </div>
        <div class="footer-right">
            <h3>A propos de nous</h3>
            <p class="footer-company-about">
            <p class="text-warning">Une entreprise des services informatiques</p>
            <div class="footer-icons">
                <a href="https://facebook.com/"><i><span class="glyphicon"><img style="height: 35px; width: 35px" src="<?php echo $this->basePath('img/icons/social-icons/skype.png'); ?>"></span></i></a>
                <a href="#"><i><span class="glyphicon"><img style="height: 35px; width: 35px" src="<?php echo $this->basePath('img/icons/social-icons/youtube.png'); ?>"></span></i></a>
                <a href="#"><i><span class="glyphicon"><img style="height: 35px; width: 35px" src="<?php echo $this->basePath('img/icons/social-icons/twitter.png'); ?>"></span></i></a>
                <a href="#"><i><span class="glyphicon"><img style="height: 35px; width: 35px" src="<?php echo $this->basePath('img/icons/social-icons/facebook.png'); ?>"></span></i></a>
                <a href="#"><i><span class="glyphicon"><img style="height: 35px; width: 35px" src="<?php echo $this->basePath('img/icons/social-icons/evernote.png'); ?>"></span></i></a>
                <a href="#"><i><span class="glyphicon"><img style="height: 35px; width: 35px" src="<?php echo $this->basePath('img/icons/social-icons/linkedin.png'); ?>"></span></i></a>
                <a href="#"><i><span class="glyphicon"><img style="height: 35px; width: 35px" src="<?php echo $this->basePath('img/icons/social-icons/google.png'); ?>"></span></i></a>
            </div>
        </div>
    </div>
</div>
<div  style="background-color: #D2D2D2">
    <div  style="background-color: #D2D2D2">
        <div class="col-xs-4"> © Sassiré 2016 All right reserved. By SASSIRE GROUP </div>
        <div class="col-xs-5"></div>
        <div class="col-xs-3">
            <ul class="list-unstyled list-inline">
                <li><a href="#">Services</a><span>&nbsp;|&nbsp;</span></li>
                <li><a href="#">Réalisations</a><span>&nbsp;|&nbsp;</span></li>
                <li><a href="#">Sources</a><span>&nbsp;|&nbsp;</span></li>
                <li><a href="#">Equipe</a><span>&nbsp;|&nbsp;</span></li>
            </ul>
        </div>
    </div>    
</div>

