<?php
echo $this->headLink()
        ->prependStylesheet($this->basePath('customer/footer/css/footer.css'))
?>
<!--<link href="https://fonts.googleapis.com/css?family=Cookie|Cormorant+Upright:400,700|Dancing+Script:700|Great+Vibes|Scheherazade|Tangerine" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Cookie|Cormorant+Upright:400,700|Dancing+Script:700|Great+Vibes|Tangerine" rel="stylesheet"> -->
<div class="row footer" style="font-family: 'Scheherazade', serif;">  
    <!-- The content of your page would go here. -->
    <div class="footer-distributed container">
        <div class="footer-left col-xs-4">
            <h3>SASSIRE<span>-IT</span></h3>
            <p class="footer-links">
                <a href="#">Services</a>                    ·                   ·
                <a href="#">R&eacute;alisations</a>                    ·
                <a href="#">Modèles</a>                    ·                   ·
            </p>            
        </div>

        <div class="footer-center col-xs-4">
            <h3>Contactez-nous</h3>
            <div class="">
                <p> <a href="#" data-placement="top"
                       title="B.P. 2861 Yaound&eacute; Messa-Cameroun"><span class="glyphicon glyphicon-home">&nbsp;&nbsp;B.P.
                            2861 Yaound&eacute Messa-Cameroun;</span></a></p>
            </div>
            <div>
                <p><a href="provincialcam@yahoo.fr" data-placement="top"
                      title="provincialcam@yahoo.fr"><span class="glyphicon glyphicon-envelope">&nbsp;&nbsp;contact@sassire.com</span></a></p>
            </div>
            <div>
                <p><a href="#" data-placement="top"
                      title="T&eacute;l&eacute;phone"><span class="glyphicon glyphicon-phone">&nbsp;&nbsp;Tél.fixe (237) 243 59 52 46</span></a></p>
            </div>
            <div>
                <p><a href="#" data-placement="top"
                      title="T&eacute;l&eacute;phone mobile "><span class="glyphicon glyphicon-phone-alt">&nbsp;&nbsp;243 566 159</span>
                    </a></p>
            </div>
        </div>
        <div class="footer-right col-xs-4">
            <h3>A propos de nous</h3>
            <p class="footer-company-about">
            <p class="text-primary" style="font-family: Dancing Script; font-size: 26px">Une entreprise des services informatiques</p>
            <div class="footer-icons">
                <a href="https://facebook.com/"><i><span class="glyphicon"><img style="height: 35px; width: 35px" src="<?php echo $this->basePath('img/icons/social-icons/skype.png'); ?>"></span></i></a>
                <a href="#"><i><span class="glyphicon"><img style="height: 35px; width: 35px" src="<?php echo $this->basePath('img/icons/social-icons/youtube.png'); ?>"></span></i></a>
                <a href="#"><i><span class="glyphicon"><img style="height: 35px; width: 35px" src="<?php echo $this->basePath('img/icons/social-icons/twitter.png'); ?>"></span></i></a>
                <a href="#"><i><span class="glyphicon"><img style="height: 35px; width: 35px" src="<?php echo $this->basePath('img/icons/social-icons/facebook.png'); ?>"></span></i></a>
                <a href="#"><i><span class="glyphicon"><img style="height: 35px; width: 35px" src="<?php echo $this->basePath('img/icons/social-icons/evernote.png'); ?>"></span></i></a>
                <a href="#"><i><span class="glyphicon"><img style="height: 35px; width: 35px" src="<?php echo $this->basePath('img/icons/social-icons/linkedin.png'); ?>"></span></i></a>
                <a href="#"><i><span class="glyphicon"><img style="height: 35px; width: 35px" src="<?php echo $this->basePath('img/icons/social-icons/google.png'); ?>"></span></i></a>
            </div>
        </div>
    </div>
</div>
<div  class="row" style="background-color: white">
    <div class="container">
        <div class="col-xs-6 copyright"> Copyright © 2016 Sassire All right reserved. By SASSIRE GROUP </div>
        <div class="col-xs-1"></div>
        <div class="col-xs-5">
            <ul class="list-unstyled list-inline">
                <li><a href="<?php echo $this->url('application/default', array('controller' => 'Index', 'action' => 'service')); ?>">Services</a><span>&nbsp;|&nbsp;</span></li>
                <li><a href="<?php echo $this->url('application/default', array('controller' => 'Index', 'action' => 'realisation')); ?>">Réalisations</a><span>&nbsp;|&nbsp;</span></li>
                <li><a href="<?php echo $this->url('application/default', array('controller' => 'Index', 'action' => 'index')); ?>">Sources</a><span>&nbsp;|&nbsp;</span></li>
                <li><a href="<?php echo $this->url('application/default', array('controller' => 'Index', 'action' => 'index')); ?>">Equipe</a><span>&nbsp;|&nbsp;</span></li>
            </ul>
        </div> 
    </div>
</div> 

