<div class="footer-bottom" style="background-color: #F3F3F3">
    <div class="container" >
        <div class="col-xs-3">
            <h4 style="font-weight: bold; opacity: 0.8">PARTENAIRES</h4>
            <ul>
                <hr>
                <li>Orange Cameroun</li>
                <hr>
                <li>MTN Cameroun</li>
                <hr>
                <li>Nexttel Cameroun</li>
                <hr>
            </ul>
        </div>
        <div class="col-xs-6">
            <h4 style="font-weight: bold; opacity: 0.8">CONTACTEZ-NOUS</h4>
            <p>Sassiré est une entreprise dont l'activité principale est centrée sur le développement des applications informatiques(web, mobile, desktop), des sites web, </p>
            <ul class="address">
                <li><i class="glyphicon glyphicon-envelope"></i> <span> Adresse:</span> Maroua Artisanal </li>
                <li><i class="fa fa-phone"></i> <span> Téléphone:</span> +928 336 2000  </li>
                <li><i class="fa fa-envelope"></i> <span> Adresse Email:</span><a href="mailto:someone@yoursite.com"> support@oxygen.com</a></li>
                <li><i class="fa fa-globe"></i> <span> Site:</span> <a href="#">www.obsic.com</a></li>
            </ul>   
        </div>
        <div class="col-xs-3">
            <h4 style="font-weight: bold; opacity: 0.8">CONTACTEZ-NOUS</h4>
            l existe deux types de blocs de texte : grilles de bloc et blocs de texte brut. Les grilles de bloc représentent les blocs de texte spécifiques à la composition en langue asiatique dans laquelle les EmBox et l’espacement des caractères s’affichent sous forme de grille. Les blocs de texte vides dans lesquels aucune grille n’est affichée sont des blocs de texte brut.

            Les blocs de texte, comme les blocs graphiques, peuvent être déplacés, redimensionnés et modifiés. L’outil utilisé pour sélectionner le bloc de texte dépend du type de modification à apporter :

        </div>
    </div>
    <div class="row" style="background-color: white">
        <div class="col-xs-4"> © Sassiré 2016 All right reserved. By AMADOU BAKARI </div>
        <div class="col-xs-5"></div>
        <div class="col-xs-3">
            <ul class="list-unstyled">
                <li><a href="#"><i class="glyphicon"></i></a></li>
                <li><a href="#"><i class="glyphicon"></i></a></li>
                <li><a href="#"><i class="glyphicon"></i></a></li>
                <li><a href="#"><i class="glyphicon"></i></a></li>
            </ul>
        </div>
    </div>