<div style="background-color: white">
    <div class="container" >
        <div class="col-xs-12">
            <div class="col-xs-3">
                <h4 style="font-weight: bold; opacity: 0.8">NOS PARTENAIRES</h4>
                <ul>
                    <hr style="color: red">
                    <li>Orange Cameroun</li>
                    <hr>
                    <li>MTN Cameroun</li>
                    <hr>
                    <li>Nexttel Cameroun</li>
                    <hr>
                </ul>
            </div>
            <div class="col-xs-5">
                <h4 style="font-weight: bold; opacity: 0.8">A PROPOS DE NOUS</h4>
                <p>Sassiré est une entreprise dont l'activité principale est centrée sur le développement des applications informatiques(web, mobile, desktop), des sites web, </p>
            </div>
            <div class="col-xs-4">
                <div class="col-xs-12">
                    <h4 style="font-weight: bold; opacity: 0.8">CONTACTEZ-NOUS</h4>
                    <ul class="address">
                        <li><i class="glyphicon glyphicon-map-marker"></i> <span> Adresse:</span> Maroua Artisanal </li>
                        <li><i class="glyphicon glyphicon-earphone"></i> <span> Téléphone:</span> +928 336 2000  </li>
                        <li><i class="glyphicon glyphicon-envelope"></i> <span> Adresse Email:</span><a href="mailto:someone@yoursite.com"> support@oxygen.com</a></li>
                        <li><i class="glyphicon glyphicon-globe"></i> <span> Site:</span> <a href="#">www.sassire.com</a></li>
                    </ul>
                </div>
                <div class="col-xs-12">

                </div>    
            </div>
        </div>        
    </div>
</div>
<div  style="background-color: #D2D2D2">
    <div  style="background-color: #D2D2D2">
        <div class="col-xs-4"> © Sassiré 2016 All right reserved. By AMADOU BAKARI </div>
        <div class="col-xs-5"></div>
        <div class="col-xs-3">
        </div>
    </div>    
</div>
