<div class="col-lg-12">
    <div class="col-lg-3 bottom">
<!--        <img class="img-responsive" src="<?php echo $this->basePath('img/logo.png'); ?>" alt=""
             width="150" height="150" />-->
    </div>
    <div class="col-lg-6">
        <img class="img-responsive center-block" src="<?php echo $this->basePath('img/ratel/logo5.png'); ?>" alt=""
             width="250" height="100" />
    </div>
    <div class="col-lg-3"></div>
</div>
