<div class="col-lg-12">
    <div class="col-lg-3 bottom">
        <div><img class="img-responsive bottom-left" src="<?php echo $this->basePath('img/logo1.png'); ?>" alt=""
                  width="200" height="0" /></div>

    </div>
    <div class="col-lg-6">
        <img class="img-responsive center-block" src="<?php echo $this->basePath('img/ratel/logo5.png'); ?>" alt=""
             width="200" height="0" />
    </div>
    <div class="col-lg-3"></div>
</div>
