<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('SASSIRE'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.png'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('customer/common/common.css'))
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/jquery.bootstrap-dropdown-hover.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Cookie|Cormorant+Upright:400,700|Dancing+Script:700|Great+Vibes|Scheherazade|Tangerine" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Cookie|Cormorant+Upright:400,700|Dancing+Script:700|Great+Vibes|Tangerine" rel="stylesheet"> 
        <link href="https://fonts.googleapis.com/css?family=Cormorant+Infant" rel="stylesheet"> 
        <link href="https://fonts.googleapis.com/css?family=Buda:300|Cormorant+Infant" rel="stylesheet"> 
        <link href="https://fonts.googleapis.com/css?family=Poiret+One" rel="stylesheet"> 
    </head>
    <body>
        <div class="row">
            <div class="col-xs-12">
                <?php echo $this->render('header.phtml'); ?>
            </div>
            <div class="col-xs-12">
                <?php echo $this->render('navbar.phtml'); ?>
            </div>
            <?php
            if (true) {
                echo '<div class="col-xs-12">';
                echo $this->render('userInfos.phtml');
                echo '</div>';
            }
            ?>
            <div class="col-xs-12">
                <?php echo $this->render('slider.phtml'); ?>
            </div>
            <div class="col-xs-12">
                <hr> 
                <?php echo $this->content; ?>
            </div>
            <div class="col-xs-12">              
                <?php echo $this->render('footer.phtml'); ?>
            </div>            
        </div>              
    </body>
</html>
