
<div class="navbar-inverse">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">                 
            <li class="scroll active"><a href="#home">ACCUEIL</a></li>                     
            <li class="scroll"><a href="#portfolio">SERVICES</a></li>
            <li class="scroll"><a href="#blog">REALISATIONS</a></li>
            <li class="scroll"><a href="#services">MODELES</a></li> 
            <li class="scroll"><a href="#pricing">EQUIPE</a></li>
            <li class="scroll"><a href="#about-us">CONTACT</a></li>                        
        </ul>
    </div>
</div>