<link href="https://fonts.googleapis.com/css?family=Cookie|Cormorant+Upright:400,700|Dancing+Script:700|Great+Vibes|Poiret+One|Quintessential|Scheherazade|Tangerine" rel="stylesheet">
<div class="navbar-inverse">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">                 
            <li class="scroll active menu-element"><a href="<?php echo $this->url('application/default', array('controller' => 'Index', 'action' => 'index')); ?>">ACCUEIL</a></li>                     
            <li class="scroll menu-element"><a href="<?php echo $this->url('application/default', array('controller' => 'Index', 'action' => 'service')); ?>">SERVICES</a></li>
            <li class="scroll menu-element"><a href="<?php echo $this->url('application/default', array('controller' => 'Index', 'action' => 'realisation')); ?>">REALISATIONS</a></li>
            <li class="scroll menu-element"><a href="#services">MODELES</a></li> 
            <li class="scroll menu-element"><a href="<?php echo $this->url('application/default', array('controller' => 'Index', 'action' => 'team')); ?>">EQUIPE</a></li>
            <li class="scroll menu-element"><a href="<?php echo $this->url('application/default', array('controller' => 'Index', 'action' => 'contact')); ?>">CONTACT</a></li>                        
        </ul>
    </div>
</div>