<div>
    <div id="myCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="3"></li>
            <li data-target="#myCarousel" data-slide-to="4"></li>
        </ol>

        <!-- Wrapper for Slides -->
        <div class="carousel-inner">
            <div class="item active">
                <!-- Set the first background image using inline CSS below. -->
                <div class="col-xs-12">
                    <div class="col-xs-6">
                        <img class="img-responsive center-block" src="<?php echo $this->basePath('customer/slider/img/slide1.png'); ?>" alt="" />  
                    </div>                    
                    <div class="carousel-caption text-justify" >
                        <div class="col-lg-6"></div>
                        <div class="col-lg-6 pull-right" style="background-color: black; opacity:  0.7;padding-bottom: 15px">
                            <h3 style=";color: #EC971F">Application Web</h3> 
                            <p>Télécharger les épreuves, les TDs des meilleurs établissements de l'Afrique ainsi que leurs corrections.</p> 
                            <a href="#" class="btn btn-primary">Voir plus</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <!-- Set the second background image using inline CSS below. -->
                <div class="col-xs-12">
                    <div class="col-xs-6">
                        <img class="img-responsive center-block" src="<?php echo $this->basePath('customer/slider/img/slide2.png'); ?>" alt="" />  
                    </div>
                    <div class="carousel-caption text-justify" >
                        <div class="col-lg-6"></div>
                        <div class="col-lg-6" style="background-color: black; opacity:  0.7;padding-bottom: 15px;">
                            <h3 style=";color: #EC971F">Web Services</h3> 
                            <p>Simplifiez vos études avec Schoolfiles. Télécharger les épreuves, traitez les et comparez vos résultats aux corrections.</p> 
                            <a href="#" class="btn btn-primary">Voir plus</a><br>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Set the third background image using inline CSS below. -->
            <div class="item">
                <div class="col-xs-12">
                    <div class="col-xs-6">
                        <img class="img-responsive center-block" src="<?php echo $this->basePath('customer/slider/img/slide3.png'); ?>" alt="" />  
                    </div>
                    <div class="carousel-caption text-justify" >
                        <div class="col-lg-6"></div>
                        <div class="col-lg-6" style="background-color: black; opacity:  0.7;padding-bottom: 15px;">
                            <h3 style=";color: #EC971F">Application Mobile</h3> 
                            <p>Simplifiez vos études avec Schoolfiles. Télécharger les épreuves, traitez les et comparez vos résultats aux corrections.</p> 
                            <a href="#" class="btn btn-primary">Voir plus</a><br>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="col-xs-12">
                    <div class="col-xs-6">
                        <img class="img-responsive center-block" src="<?php echo $this->basePath('customer/slider/img/slide4.png'); ?>" alt="" />  
                    </div>
                    <div class="carousel-caption text-justify" >
                        <div class="col-lg-6"></div>
                        <div class="col-lg-6" style="background-color: black; opacity:  0.7;padding-bottom: 15px;">
                            <h3 style=";color: #EC971F">IT-Consulting</h3> 
                            <p>Simplifiez vos études avec Schoolfiles. Télécharger les épreuves, traitez les et comparez vos résultats aux corrections.</p> 
                            <a href="#" class="btn btn-primary">Voir plus</a><br>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="col-xs-12">
                    <div class="col-xs-6">
                        <img class="img-responsive center-block" src="<?php echo $this->basePath('customer/slider/img/slide5.png'); ?>" alt="" />  
                    </div>
                    <div class="carousel-caption text-justify" >
                        <div class="col-lg-6"></div>
                        <div class="col-lg-6" style="background-color: black; opacity:  0.7;padding-bottom: 15px;">
                            <h3 style=";color: #EC971F">Site Web</h3> 
                            <p>Simplifiez vos études avec Schoolfiles. Télécharger les épreuves, traitez les et comparez vos résultats aux corrections.</p> 
                            <a href="#" class="btn btn-primary">Voir plus</a><br>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>
    </div>
</div>
<script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
</script>