
<div class="col-xs-12">
    <div class="col-xs-7">
    </div>
    <div class="col-xs-3">
        <?php
        echo '<p>Bienvenu <b> AMADOU BAKARI  |  <a data-toggle="modal" data-target="#reset-password-form" href="#">   Déconnexion</a></b></p>';
        ?>
    </div>
    <div class="col-xs-1">
        <ul class="nav navbar-top-links navbar-right">
            <li class="dropdown">
                <a aria-expanded="false" class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                    <i class="fa fa-envelope"></i>  <span class="badge warning">16</span>
                </a>
                <ul class="dropdown-menu dropdown-messages">
                    <li>
                        <div class="dropdown-messages-box">
                            <a href="profile.html" class="pull-left">
                                <img  height="50" width="50" class="img-responsive img-circle" src="<?php echo $this->basePath('customer/images/slider/4.jpg'); ?>">
                            </a>
                            <div class="media-body">
                                <small class="pull-right">46h ago</small>
                                <strong>Passang Gamaliel</strong><br>
                                <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
                            </div>
                        </div>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <div class="dropdown-messages-box">
                            <a href="profile.html" class="pull-left">
                                <img alt="image" class="img-circle" src="img/a4.jpg">
                            </a>
                            <div class="media-body ">
                                <small class="pull-right text-navy">5h ago</small>
                                <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>
                                <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
                            </div>
                        </div>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <div class="text-center link-block">
                            <a href="<?php echo $this->url('application/default', array('controller' => 'Index', 'action' => 'inboxmsg')) ?>">
                                <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
                            </a>
                        </div>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    <img height="75" width="75" class="img-responsive img-circle" src="<?php echo $this->basePath('customer/images/slider/4.jpg'); ?>" alt="" />
</div>






<div class="modal fade col-lg-12" id="reset-password-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div>
        <div class="col-lg-4"></div>
        <div class="col-lg-4 aligncenter" style="border: 2px solid #CBE6F4;background-color: white">
            <form class="form-signin" method="POST">   
                <!--        <h2 class="form-signin-heading text-center">Authentification</h2>-->
                <br><br> <br><br>
                <div class="text-center">
                    <img src="<?php echo $this->basePath('img/logo.png'); ?>" alt=""
                         style="width: 100px; height: 100px; margin-top: 15px" /><br><br>
                </div>
                <div>
                    <input type="text" value="<?php //echo $login;         ?>" id="login" class="form-control active" name="login" placeholder="login" required="true" autofocus="" />
                </div><br>  
                <div>
                    <input type="password" value="" id="password" class="form-control" name="password" placeholder="Password" required="true"/> 
                </div>  
                <div>
                    <label class="checkbox">
                        <input type="checkbox" value="remember-me" id="rememberMe" name="rememberMe" style="margin-left: 5px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Remember me
                    </label>
                    <a href="#" data-toggle="modal" data-target="#reset-password-form">Mot de passe oublié?</a>
                    <a href="#" data-toggle="modal" data-target="#reset-password-form">Créer un nouveau compte</a>
                </div>
                <div class="form-group center-block col-xs-12">
                    
                    <button type="submit" class="btn btn-primary" name="send" id="send" data-loading-text="Connexion ...">&nbsp;Connexion <span class="glyphicon glyphicon-log-in"></span></button>
                    <button type="submit" class="btn btn-warning" name="cancel" id="cancel" data-loading-text="annuler ...">&nbsp;&nbsp;Annuler&nbsp; <span class="glyphicon glyphicon-log-in"></span></button>
                    <div id="loader">
                    </div><br><br>
                </div>
                <div class="col-lg-offset-2">
                    <p class="text-danger"> <?php //echo $msg;         ?></p>
                </div><br><br>
            </form>
        </div>
        <div class="col-lg-4"></div>
    </div>
</div>
<!-- Formulaire pour la resstauration du mot de passe -->
<div class="modal fade" id="reset-password-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form class="form-horizontal col-²lg-12" method="POST" enctype="multipart/form-data" style="border: 2px solid #CBE6F4;background-color: white">
                <div>
                    <br/>
                    <p class="text-center text-primary" style="font-family: serif; font-size: 14px; font-weight: bold">Restitution du mot de passe </p>
                    <hr>
                    <div class="form-group">
                        <label for="email" class="col-sm-3 control-label">Email :</label>
                        <div class="col-sm-8">
                            <input type="text"  class="form-control"  name="email" id="email" placeholder="Mettez votre adresse email">
                        </div>
                    </div>
                    <br>
                </div>
                <div class="modal-footer modal-arrow">
                    <a href="#" type="button" class="btn btn-primary">Envoyer</a>
                    <button type="button" class="btn btn-warning" data-dismiss="modal">Annuler</button>               
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).ready(
            function() {
                $('#send').mousedown(
                        function() {
                            if ($('#login').val() !== "" && $('#password').val() !== "") {
                                $('#loader').append('<img src="<?php echo $this->basePath('img/ajax-loader/connection-loader.gif'); ?>">').fadeIn('fast', 0.2);
                            }

                        });
            }
    );
</script>












