
<div class="col-xs-12">
    <div class="col-xs-5">
    </div>
    <div class="col-xs-3">
        <?php
        if (true) {
            echo '<div class="col-xs-8">
                    <p>Bienvenu <b> AMADOU BAKARI  |  <a data-toggle="modal" data-target="#reset-password-form" href="#">   Déconnexion</a></b></p>
                    </div>';
            echo '<div class="col-xs-4">
                <img height="75" width="75" class="img-responsive img-circle" src="' . $this->basePath('customer/images/slider/4.jpg') . '" alt="" />
                </div>';
        } else {
            echo '<p><b><a data-toggle="modal" data-target="#reset-password-form" href="#">   Connexion</a></b></p>';
        }
        ?>
    </div>
    <div class="col-xs-4">
        <div class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle glyphicon glyphicon-envelope" ><span class="badge">42</span></a>
            <ul class="dropdown-menu">
                <div class="col-xs-12" style="border-bottom: 2px solid #F4F4F4 ">
                    <li><a href="#">
                            <div class="col-xs-12">
                                <div class="col-xs-1">
                                    <img src="<?php echo $this->basePath('img/logo.png'); ?>" alt=""
                                         width="30" height="30" />
                                </div>
                                <div class="col-xs-11">
                                    <div class="msg-header col-xs-12">
                                        <div class="col-xs-8" style="font-weight: bold">Passang Gamalier</div>
                                        <div class="col-xs-4"><span class="badge bg-primary">20 hours Ago</span></div>
                                    </div>
                                    <div class="col-xs-12">
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
                                    </div>
                                    <div class="col-xs-12" style="font-weight: bold">Since Monday, 14th March 2016</div>                                    
                                </div>
                            </div>
                        </a>
                    </li>
                </div>
                <div class="col-xs-12" style="border-bottom: 2px solid #F4F4F4 ">
                    <li><a href="#">
                            <div class="col-xs-12">
                                <div class="col-xs-1">
                                    <img src="<?php echo $this->basePath('img/logo.png'); ?>" alt=""
                                         width="30" height="30" />
                                </div>
                                <div class="col-xs-11">
                                    <div class="msg-header col-xs-12">
                                        <div class="col-xs-8" style="font-weight: bold">Passang Gamalier</div>
                                        <div class="col-xs-4"><span class="badge bg-primary">20 hours Ago</span></div>
                                    </div>
                                    <div class="col-xs-12">
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
                                    </div>
                                    <div class="col-xs-12" style="font-weight: bold">Since Monday, 14th March 2016</div>                                    
                                </div>
                            </div>
                        </a>
                    </li>
                </div><div class="col-xs-12" style="border-bottom: 2px solid #F4F4F4 ">
                    <li><a href="#">
                            <div class="col-xs-12">
                                <div class="col-xs-1">
                                    <img src="<?php echo $this->basePath('img/logo.png'); ?>" alt=""
                                         width="30" height="30" />
                                </div>
                                <div class="col-xs-11">
                                    <div class="msg-header col-xs-12">
                                        <div class="col-xs-8" style="font-weight: bold">Passang Gamalier</div>
                                        <div class="col-xs-4"><span class="badge bg-primary">20 hours Ago</span></div>
                                    </div>
                                    <div class="col-xs-12">
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
                                    </div>
                                    <div class="col-xs-12" style="font-weight: bold">Since Monday, 14th March 2016</div>                                    
                                </div>
                            </div>
                        </a>
                    </li>
                </div>             
                <div class="arrow">
                    <li><a href="<?php echo $this->url('application/default', array('controller' => 'Index', 'action' => 'inboxmsg')); ?>">
                            <div> Voir tous</div> 
                        </a>
                    </li>
                </div>
            </ul>
        </div>
    </div>   
</div>






<div class="modal fade col-lg-12" id="reset-password-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="padding-top: 10%">
    <div>
        <div class="col-lg-4"></div>
        <div class="col-lg-4 aligncenter" style="border: 2px solid #CBE6F4; background-color: white">
            <div class="arrow"></div>
            <div>
                <form class="form-signin" method="POST">   
                    <!--        <h2 class="form-signin-heading text-center">Authentification</h2>-->
                    <br><br> <br><br>
                    <div class="text-center">
                        <img src="<?php echo $this->basePath('img/logo.png'); ?>" alt=""
                             style="width: 100px; height: 100px; margin-top: 15px" /><br><br>
                    </div>
                    <div>
                        <input type="text" value="<?php //echo $login;                               ?>" id="login" class="form-control active" name="login" placeholder="login" required="true" autofocus="" />
                    </div><br>  
                    <div>
                        <input type="password" value="" id="password" class="form-control" name="password" placeholder="Password" required="true"/> 
                    </div> 
                    <div>
                        <br>
                        <label class="checkbox">
                            <input type="checkbox" value="remember-me" id="rememberMe" name="rememberMe">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Remember me
                        </label>
                    </div>
                    <div class="form-group center-block col-xs-12">
                        <br><br>
                        <button type="submit" class="btn btn-primary" name="send" id="send" data-loading-text="Connexion ...">&nbsp;Connexion <span class="glyphicon glyphicon-log-in"></span></button>
                        <button type="submit" class="btn btn-warning" name="cancel" id="cancel" data-loading-text="annuler ...">&nbsp;&nbsp;Annuler&nbsp; <span class="glyphicon glyphicon-log-in"></span></button>
                        <div id="loader">
                        </div><br><br>
                    </div>
                    <div>
                        <div class="col-xs-6">
                            <a href="#" data-toggle="modal" data-target="#reset-password-form">Mot de passe oublié?</a>
                            <br><br>
                        </div>
                        <div class="col-xs-6">
                            <a href="#" data-toggle="modal" data-target="#reset-password-form">Créer un nouveau compte</a>
                            <br><br>
                        </div>
                    </div>
                    <div class="col-lg-offset-2">
                        <p class="text-danger"> <?php //echo $msg;                               ?></p>
                    </div><br><br>
                </form>
            </div>

        </div>
        <div class="col-lg-4"></div>
    </div>
</div>
<!-- Formulaire pour la resstauration du mot de passe -->
<div class="modal fade" id="reset-password-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form class="form-horizontal col-²lg-12" method="POST" enctype="multipart/form-data" style="border: 2px solid #CBE6F4;background-color: white">
                <div>
                    <br/>
                    <p class="text-center text-primary" style="font-family: serif; font-size: 14px; font-weight: bold">Restitution du mot de passe </p>
                    <hr>
                    <div class="form-group">
                        <label for="email" class="col-sm-3 control-label">Email :</label>
                        <div class="col-sm-8">
                            <input type="text"  class="form-control"  name="email" id="email" placeholder="Mettez votre adresse email">
                        </div>
                    </div>
                    <br>
                </div>
                <div class="modal-footer modal-arrow">
                    <a href="#" type="button" class="btn btn-primary">Envoyer</a>
                    <button type="button" class="btn btn-warning" data-dismiss="modal">Annuler</button>               
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).ready(
            function() {
                $('#send').mousedown(
                        function() {
                            if ($('#login').val() !== "" && $('#password').val() !== "") {
                                $('#loader').append('<img src="<?php echo $this->basePath('img/ajax-loader/connection-loader.gif'); ?>">').fadeIn('fast', 0.2);
                            }

                        });
            }
    );
</script>












