<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.png'))
                ->prependStylesheet($this->basePath('customer/realisation/css/main.css'))
                ->prependStylesheet($this->basePath('customer/realisation/css/animate.min.css'))
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('customer/realisation/js/main.js'))
        ;
        ?>

    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="heading text-center col-sm-8 col-sm-offset-2 wow fadeInUp" data-wow-duration="1200ms" data-wow-delay="300ms">
                    <h2>Nos REALISATIONS</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim ad minim veniam</p>
                </div>
            </div>
            <div class="blog-posts">
                <div class="row">
                    <div>
                        <div class="col-sm-2"></div>
                        <div class="col-sm-8 wow fadeInUp center-block" data-wow-duration="1000ms" data-wow-delay="600ms">
                            <div class="entry-header">
                                <h3><a href="#">GP-CICM (Application de gestion de personnels du Coeur Immaculée Marie)</a></h3>
                                <span class="date">June 26, 2016</span>
                                <span class="cetagory">in <strong>Photography</strong></span>
                            </div>
                            <div class="post-thumb">
                                <div id="post-carousel"  class="carousel slide" data-ride="carousel">
                                    <ol class="carousel-indicators">
                                        <li data-target="#post-carousel" data-slide-to="0" class="active"></li>
                                        <li data-target="#post-carousel" data-slide-to="1"></li>
                                        <li data-target="#post-carousel" data-slide-to="2"></li>
                                        <li data-target="#post-carousel" data-slide-to="3"></li>
                                        <li data-target="#post-carousel" data-slide-to="4"></li>
                                    </ol>
                                    <div class="carousel-inner">
                                        <div class="item active">
                                            <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco1.PNG'); ?>" alt=""></a>
                                        </div>
                                        <div class="item">
                                            <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco2.PNG'); ?>" alt=""></a>
                                        </div>
                                        <div class="item">
                                            <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco3.PNG'); ?>" alt=""></a>
                                        </div>
                                        <div class="item">
                                            <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco4.PNG'); ?>" alt=""></a>
                                        </div>
                                        <div class="item">
                                            <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco5.PNG'); ?>" alt=""></a>
                                        </div>
                                    </div>                               
                                    <a class="blog-left-control" href="#post-carousel" role="button" data-slide="prev"><i class="fa fa-angle-left"></i></a>
                                    <a class="blog-right-control" href="#post-carousel" role="button" data-slide="next"><i class="fa fa-angle-right"></i></a>
                                </div>                            
                                <div class="post-meta">
                                    <span><i class="fa fa-comments-o"></i> 3 Comments</span>
                                    <span><i class="fa fa-heart"></i> 0 Likes</span> 
                                </div>
                                <div class="post-icon">
                                    <i class="fa fa-picture-o"></i>
                                </div>
                            </div>                            
                            <div class="entry-content">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                            </div>
                        </div>
                        <div class="col-sm-2"></div>
                    </div>
                    <div class="col-sm-4 wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="400ms">
                        <div class="post-thumb">
                            <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/service/img/mobile (1).png'); ?>" alt=""></a> 
                            <div class="post-meta">
                                <span><i class="fa fa-comments-o"></i> 3 Comments</span>
                                <span><i class="fa fa-heart"></i> 0 Likes</span> 
                            </div>
                            <div class="post-icon">
                                <i class="fa fa-pencil"></i>
                            </div>
                        </div>
                        <div class="entry-header">
                            <h3><a href="#">Lorem ipsum dolor sit amet consectetur adipisicing elit</a></h3>
                            <span class="date">June 26, 2014</span>
                            <span class="cetagory">in <strong>Photography</strong></span>
                        </div>
                        <div class="entry-content">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                        </div>
                    </div>
                    <div class="col-sm-4 wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="600ms">
                        <div class="post-thumb">
                            <div id="post-carousel"  class="carousel slide" data-ride="carousel">
                                <ol class="carousel-indicators">
                                    <li data-target="#post-carousel" data-slide-to="0" class="active"></li>
                                    <li data-target="#post-carousel" data-slide-to="1"></li>
                                    <li data-target="#post-carousel" data-slide-to="2"></li>
                                </ol>
                                <div class="carousel-inner">
                                    <div class="item active">
                                        <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/service/img/mobile (1).png'); ?>" alt=""></a>
                                    </div>
                                    <div class="item">
                                        <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/service/img/mobile (1).png'); ?>" alt=""></a>
                                    </div>
                                    <div class="item">
                                        <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/service/img/mobile (1).png'); ?>" alt=""></a>
                                    </div>
                                </div>                               
                                <a class="blog-left-control" href="#post-carousel" role="button" data-slide="prev"><i class="fa fa-angle-left"></i></a>
                                <a class="blog-right-control" href="#post-carousel" role="button" data-slide="next"><i class="fa fa-angle-right"></i></a>
                            </div>                            
                            <div class="post-meta">
                                <span><i class="fa fa-comments-o"></i> 3 Comments</span>
                                <span><i class="fa fa-heart"></i> 0 Likes</span> 
                            </div>
                            <div class="post-icon">
                                <i class="fa fa-picture-o"></i>
                            </div>
                        </div>
                        <div class="entry-header">
                            <h3><a href="#">Lorem ipsum dolor sit amet consectetur adipisicing elit</a></h3>
                            <span class="date">June 26, 2014</span>
                            <span class="cetagory">in <strong>Photography</strong></span>
                        </div>
                        <div class="entry-content">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                        </div>
                    </div>
                    <div class="col-sm-4 wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="800ms">
                        <div class="post-thumb">
                            <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/service/img/mobile (1).png'); ?>" alt=""></a>
                            <div class="post-meta">
                                <span><i class="fa fa-comments-o"></i> 3 Comments</span>
                                <span><i class="fa fa-heart"></i> 0 Likes</span> 
                            </div>
                            <div class="post-icon">
                                <i class="fa fa-video-camera"></i>
                            </div>
                        </div>
                        <div class="entry-header">
                            <h3><a href="#">Lorem ipsum dolor sit amet consectetur adipisicing elit</a></h3>
                            <span class="date">June 26, 2014</span>
                            <span class="cetagory">in <strong>Photography</strong></span>
                        </div>
                        <div class="entry-content">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                        </div>
                    </div>   
                    <div>
                        <div class="col-sm-2"></div>
                        <div class="col-sm-8 wow fadeInUp center-block" data-wow-duration="1000ms" data-wow-delay="600ms">
                            <div class="entry-header">
                                <h3><a href="#">GP-CICM (Application de gestion de personnels du Coeur Immaculée Marie)</a></h3>
                                <span class="date">June 26, 2016</span>
                                <span class="cetagory">in <strong>Photography</strong></span>
                            </div>
                            <div class="post-thumb">
                                <div id="post-carousel"  class="carousel slide" data-ride="carousel">
                                    <ol class="carousel-indicators">
                                        <li data-target="#post-carousel" data-slide-to="0" class="active"></li>
                                        <li data-target="#post-carousel" data-slide-to="1"></li>
                                        <li data-target="#post-carousel" data-slide-to="2"></li>
                                        <li data-target="#post-carousel" data-slide-to="3"></li>
                                        <li data-target="#post-carousel" data-slide-to="4"></li>
                                    </ol>
                                    <div class="carousel-inner">
                                        <div class="item active">
                                            <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco1.PNG'); ?>" alt=""></a>
                                        </div>
                                        <div class="item">
                                            <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco2.PNG'); ?>" alt=""></a>
                                        </div>
                                        <div class="item">
                                            <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco3.PNG'); ?>" alt=""></a>
                                        </div>
                                        <div class="item">
                                            <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco4.PNG'); ?>" alt=""></a>
                                        </div>
                                        <div class="item">
                                            <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco5.PNG'); ?>" alt=""></a>
                                        </div>
                                    </div>                               
                                    <a class="blog-left-control" href="#post-carousel" role="button" data-slide="prev"><i class="fa fa-angle-left"></i></a>
                                    <a class="blog-right-control" href="#post-carousel" role="button" data-slide="next"><i class="fa fa-angle-right"></i></a>
                                </div>                            
                                <div class="post-meta">
                                    <span><i class="fa fa-comments-o"></i> 3 Comments</span>
                                    <span><i class="fa fa-heart"></i> 0 Likes</span> 
                                </div>
                                <div class="post-icon">
                                    <i class="fa fa-picture-o"></i>
                                </div>
                            </div>                            
                            <div class="entry-content">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                            </div>
                        </div>
                        <div class="col-sm-2"></div>
                    </div>
                </div>
                <div class="load-more wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="500ms">
                    <a href="#" class="btn-loadmore"><i class="fa fa-repeat"></i> Load More</a>
                </div>                
            </div>
        </div>
    </body>
</html>
