<!DOCTYPE html>
<html lang="en">

    <head>

        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.png'))
                ->prependStylesheet($this->basePath('customer/service/css/agency.css'))
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('customer/service/js/classie.js'))
                ->prependFile($this->basePath('customer/service/js/cbpAnimatedHeader.js'))
                ->prependFile($this->basePath('customer/service/js/jqBootstrapValidation.js'))
                ->prependFile($this->basePath('customer/service/js/contact_me.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('customer/service/js/agency.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>


        <!-- Custom CSS -->
        <!--        <link href="customer/service/css/agency.css" rel="stylesheet">-->

    </head>

    <body id="page-top" class="index">
        <!-- Services Section -->

        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading element-item">Services</h2>
                    <h3 class="section-subheading text-muted element-sub-item">La satisfaction du client est au coeur de notre philosophie !!!</h3>
                </div>
            </div>
            <div class="row text-center">
                <div class="col-md-4">
                </div>
                <div class="col-md-4" id="application-web">
                    <h3 class="service-heading service-item" >Application Web</h3>
                    <a href="#portfolioModal9" class="portfolio-link" data-toggle="modal">
                        <img title="voir détails" width="300" height="450" src="<?php echo $this->basePath('customer/service/img/cicmaco4.png'); ?>" class="center-block img-responsive img-circle" alt="Voir details">
                    </a> 
                    <h4 class="service-heading" >Développement des Applications Web</h4>
                    <p class="text-muted service-item-label">Vous êtes une Entreprise, une Société, une Organisation, un Etablissement, une Institution et vous avez besoin d'une application. N'hésitez pas à nous contacter <a href="https://www.sassire.com">sassire.com</a> .</p>
                </div>
                <div class="col-md-4">
                </div>
            </div>
            <div class="row text-center" >
                <div class="col-md-4" id="site-web">
                    <h3 class="service-heading service-item">Site-Web</h3>
                    <a href="#portfolioModal6" class="portfolio-link" data-toggle="modal">
                        <img width="300" height="450" src="<?php echo $this->basePath('customer/service/img/responsive (2).jpg'); ?>" title="Cliquez pour voir les détails" class="center-block img-responsive img-circle img-feature-1" alt="">
                    </a> 
                    <h4 class="service-heading">Conception des Sites Web</h4>
                    <p class="text-muted service-item-label">Vous avez besoin d'une Visibilité, d'une Notoriété, une Extension, etc. Vous auriez besoin d'un Site Web et c'est l'affaire de <a href="https://www.sassire.com"></a>affaire.</p>
                </div>
                <div class="col-md-4 center-block" id="web-services">
                    <h3 class="service-heading service-item">Web Services</h3>
                    <a href="#portfolioModal7" class="portfolio-link" data-toggle="modal">
                        <img title="Cliquez pour voir les détails" width="300" height="450" src="<?php echo $this->basePath('customer/service/img/ws (1).jpg'); ?>" class="center-block img-responsive img-circle img-feature-1" alt="">
                    </a> 
                    <h4 class="service-heading">Conception des Services Web Service</h4>
                    <p class="text-muted service-item-label">Vous avez besoin de superviser, de faire le suivi du fonctionnement d'un systèle, d'une plateforme via une tierce application mobile, veuillez nous contacter sur <a href="https://www.sassire.com">sassire.com</a></p>
                </div>
                <div class="col-md-4" id="it-consulting">
                    <h3 class="service-heading service-item">IT-Consulting</h3>
                    <a href="#portfolioModal10" class="portfolio-link" data-toggle="modal">
                        <img title="Cliquez pour voir les détails" width="300" height="450" src="<?php echo $this->basePath('customer/service/img/consulting.jpg'); ?>" class="center-block img-responsive img-circle img-feature-1" alt="">
                    </a> 
                    <h4 class="service-heading">IT-Consulting</h4>
                    <p class="text-muted service-item-label">Vous avez besoin des conseils, des directives dans le processus d'informatisation et d'automatisation des vos problèmes, faites appel à <a href="https://www.sassire.com">Sassiré group</a> .</p>
                </div>
            </div>
            <div class="row text-center" id="application-mobile">
                <div class="col-md-4">
                </div>
                <div class="col-md-4">
                    <h3 class="service-heading service-item">Application-Mobile</h3>
                    <a href="#portfolioModal8" class="portfolio-link" data-toggle="modal">
                        <img title="Cliquez pour voir les détails" width="300" height="450" src="<?php echo $this->basePath('customer/service/img/mobile (1).png'); ?>" class="center-block img-responsive img-circle img-feature-1" alt="">
                    </a> 
                    <h4 class="service-heading">Développement des Applications Mobiles</h4>
                    <p class="text-muted service-item-label">Vous voulez étendre votre entreprise, faciliter l'accès aux informations, accoître la production et communiquer avec vos clients, l'application mobile serait une solution fiable et facile à mettre en place. Veuillez nous contacter à <a href="https://www.sassire.com">Sassiré group</a>. </p>
                </div>
                <div class="col-md-4 center-block">
                </div>
            </div>            
        </div>

        <!-- Portfolio Grid Section -->
        <!-- About Section -->
        <div class="container">
            <br><br><br><br><br><br>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading element-item">A Propos de nous</h2>
                    <h3 class="section-subheading text-muted element-sub-item">La génèse de l'entreprise SASSIRE GROUP</h3>
                </div>
            </div>

            <br><br><br>
            <div class="row">
                <div class="col-lg-12">
                    <ul class="timeline">
                        <li>
                            <div class="timeline-image">
                                <img class="img-circle img-responsive" src="<?php echo $this->basePath('customer/service/img/about/1.jpg'); ?>" title="Cliquer sur l'image pour l'agrandir" alt="">
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4 class="team-item-title">2013-2014</h4>
                                    <h4 class="subheading">Commencement</h4>
                                </div>
                                <div class="timeline">
                                    <p class="p-service">Une équipe de 02 personnes<br>
                                        Développement des applications Web et des sites Web.</p>
                                </div>
                            </div>
                        </li>
                        <li class="timeline-inverted">
                            <div class="timeline-image">
                                <img class="img-circle img-responsive" src="<?php echo $this->basePath('customer/service/img/about/2.jpg'); ?>" alt="">
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4 class="team-item-title">Mars 2014</h4>
                                    <h4 class="subheading">Innovation dans le monde des applications mobiles</h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted p-service">Equipe de 03 personnes<br>
                                        Développement des applications Mobiles pour Android<br>
                                        Développement des services Web</p>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="timeline-image">
                                <img class="img-circle img-responsive" src="<?php echo $this->basePath('customer/service/img/about/3.jpg'); ?>" alt="">
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4 class="team-item-title">Décembre 2014-2015</h4>
                                    <h4 class="subheading">Innovation Technologique</h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted p-service">Utilisation des Technologies WEB 2.0 :<br>
                                        Bootstrap Twitter<br>
                                        JQuery<br>
                                        AJAX</p>
                                </div>
                            </div>
                        </li>
                        <li class="timeline-inverted">
                            <div class="timeline-image">
                                <img class="img-circle img-responsive" src="<?php echo $this->basePath('customer/service/img/about/4.jpg'); ?>" alt="">
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4 class="team-item-title">2016</h4>
                                    <h4 class="subheading">Intégration du IT-Consulting</h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted p-service">Conesil et directives dans l'informatisation et l'automatisation des Problèmes</p>
                                </div>
                            </div>
                        </li>
                        <li class="timeline-inverted">
                            <div class="timeline-image">
                                <h4>Notre 
                                    <br>Bel
                                    <br>Historique !</h4>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Team Section -->
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading element-item">Notre Equipe</h2>
                    <h3 class="section-subheading text-muted element-sub-item">Une communauté des Ingénieurs Chevronnés</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <div class="team-member">
                        <img src="<?php echo $this->basePath('customer/service/img/about/4.jpg'); ?>" class="img-responsive img-circle" alt="">
                        <h4 class="team-item">Passang Gamaliel</h4>
                        <p class="text-muted">Architecte Système</p>
                        <ul class="list-inline social-buttons">
                            <li><a href="#"><i class="fa fa-twitter"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="team-member">
                        <a href="#"  data-toggle="modal" data-target="#team1cv">
                            <img src="<?php echo $this->basePath('customer/team/img/team3.png'); ?>" title="Voir détails" class="img-responsive img-circle" alt="">
                        </a>
                        <h4 class="team-item">Tony Parker The Freeman II</h4>
                        <p class="text-muted">Architecte Système/Ingénieur de Conception des solutions Informatques </p>
                        <ul class="list-inline social-buttons">
                            <li><a href="#"><i class="fa fa-twitter"></i></a>
                            </li>
                            <li><a href="https://www.facebook.com/amadoubakari.bakari"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="team-member">
                        <img src="<?php echo $this->basePath('customer/service/img/team/3.jpg'); ?>" class="img-responsive img-circle" alt="">
                        <h4 class="team-item">Bivagai Omar</h4>
                        <p class="text-muted">Lead Developer</p>
                        <ul class="list-inline social-buttons">
                            <li><a href="#"><i class="fa fa-twitter"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <p class="large text-muted"></p>
                </div>
            </div>
        </div>




        <div class="portfolio-modal modal fade" id="portfolioModal6" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-content">
                <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                        <div class="rl">
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="modal-body">
                                <!-- Project Details Go Here -->
                                <h2>Sites Web</h2>
                                <p class="item-intro text-muted">Conception des Sites Web</p>
                                <img class="img-responsive img-centered" src="<?php echo $this->basePath('customer/service/img/responsive (2).jpg'); ?>" alt="">
                                <p>Soyez Visible sur la Toile Mondiale, Augmenter votre popularité et maximiser votre clientèle via un site:</p>
                                <h3>Nous concevons toute catégorie de site</h3>
                                <ul class="list-unstyled">
                                    <li>
                                        <h4>sites e-commerce</h4>
                                        <p>Les sites marchands permettent de vendre directement vos produits aux internautes qui procèdent au paiement directement en ligne.</p>
                                    </li>
                                    <li> 
                                        <h4> Sites Vitrines</h4>
                                        <p>Rôle d’information mettant en avant l’image de marque de votre entreprise, en présentant votre activité, vos produits, vos services.</p>
                                    </li>
                                    <li>
                                        <h4>Sites Institutionnels</h4>
                                        <p>Présentation de l’organisation et des valeurs de l’entreprise, par la description de l’activité, la transmission de chiffres clés et des ‘informations nécessaires au public ciblé.</p>
                                    </li>
                                    <li>
                                        <h4>Sites Personnels</h4>
                                        <p> Sites réalisés par des particuliers, le plus souvent par passion pour un sujet précis.</p>
                                    </li>                                    
                                    <li>
                                        <h4> Site communautaires</h4>
                                        <p>Les réseaux sociaux permettent aux internautes de se réunir autour d’un intérêt commun, d’un partage d’informations.</p>
                                    </li>
                                    <li>
                                        <h4> Sites Blog</h4>
                                        <p>Plus ouverts que les sites personnels; les visiteurs peuvent laisser leurs commentaires.</p>
                                    </li>
                                </ul>
                                <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Fermer</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="portfolio-modal modal fade" id="portfolioModal7" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-content">
                <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                        <div class="rl">
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="modal-body">
                                <!-- Project Details Go Here -->
                                <h2>Web Services </h2>
                                <p class="item-intro text-muted">Conception des WEB Services</p>
                                <img class="img-responsive img-centered" src="<?php echo $this->basePath('customer/service/img/ws (1).jpg'); ?>" alt="">
                                <p>Vous avez besoin de superviser, de faire le suivi du fonctionnement d'un systèle, d'une plateforme via une tierce application mobile, veuillez nous contacter</p>
                                <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close Project</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="portfolio-modal modal fade" id="portfolioModal8" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-content">
                <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                        <div class="rl">
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="modal-body">
                                <!-- Project Details Go Here -->
                                <h2>Application mobile</h2>
                                <p class="item-intro text-muted">Conception des Applications Mobiles</p>
                                <img class="img-responsive img-centered" src="<?php echo $this->basePath('customer/service/img/mobile (1).png'); ?>" alt="">
                                <p>Etendez vos entreprises, augmentez la production des vos employés, facilitez l'accès aux informations grâce aux applications mobiles.</p>
                                <h3>Catégories des Applications Mobiles que nous développns</h3>
                                <ul>
                                    <li>Applications de Géolocalisation</li>
                                    <li>Application mobile de e-commerce</li>
                                    <li>Application Mobile pour Web Service</li>
                                </ul>
                                <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Fermer</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="portfolio-modal modal fade" id="portfolioModal9" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-content">
                <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                        <div class="rl">
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="modal-body">
                                <!-- Project Details Go Here -->
                                <h2>Application Web</h2>
                                <p class="item-intro text-muted">Développement des Applications Web ....</p>
                                <img class="img-responsive img-centered" src="<?php echo $this->basePath('customer/service/img/cicmaco5.png'); ?>" alt="">
                                <p>Votre application accessible et disponible 24h/24 et 7jr/7. La sécurité et la confifentialité de vos données. N'ignorez pas l'aspect Adaptabilité de l'application sur n'importe quel terminal (Tablette, SmartPhone, Ordinateur). chez &nbsp;<a href="https://www.behance.net/MathavanJaya">Sassire group</a> </p>
                                <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Fermer</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="portfolio-modal modal fade" id="portfolioModal10" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-content">
                <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                        <div class="rl">
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="modal-body">
                                <!-- Project Details Go Here -->
                                <h2>Site Web</h2>
                                <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
                                <img class="img-responsive img-centered" src="<?php echo $this->basePath('customer/service/img/consulting.jpg'); ?>" alt="">
                                <p>Dreams is a free PSD web template built by <a href="https://www.behance.net/MathavanJaya">Mathavan Jaya</a>. Dreams is a modern one page web template designed for almost any purpose. It’s a beautiful template that’s designed with the Bootstrap framework in mind.</p>
                                <p>You can download the PSD template in this portfolio sample item at <a href="http://freebiesxpress.com/gallery/dreams-free-one-page-web-template/">FreebiesXpress.com</a>.</p>
                                <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close Project</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="portfolio-modal modal fade" id="portfolioModal11" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-content">
                <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                        <div class="rl">
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="modal-body">
                                <!-- Project Details Go Here -->
                                <h2>Site Web</h2>
                                <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
                                <img class="img-responsive img-centered" src="<?php echo $this->basePath('customer/service/img/native.png'); ?>" alt="">
                                <p>Dreams is a free PSD web template built by <a href="https://www.behance.net/MathavanJaya">Mathavan Jaya</a>. Dreams is a modern one page web template designed for almost any purpose. It’s a beautiful template that’s designed with the Bootstrap framework in mind.</p>
                                <p>You can download the PSD template in this portfolio sample item at <a href="http://freebiesxpress.com/gallery/dreams-free-one-page-web-template/">FreebiesXpress.com</a>.</p>
                                <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close Project</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade col-lg-12" id="team1cv" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="padding-top: 10%">
            <div class="col-lg-3"></div>
            <div class="col-lg-6 aligncenter" style="border: 2px solid #CBE6F4;background-color: white;padding-top: 2%">
                <div class="cv-title col-xs-12">CV Amadou Bakari</div>
                <div class="col-xs-12">
                    <div class="col-xs-4">
                        <img class="img-responsive img-circle" src="<?php echo $this->basePath('customer/team/img/team3.png'); ?>" alt="">
                    </div>
                    <div class="col-xs-8">
                        <ul class="list-unstyled">
                            <li class="cv-label">Nom :<span class="cv-value"> &nbsp; AMADOU BAKARI</span></li>
                            <li class="cv-label">Téléphone :<span class="cv-value">&nbsp;+237 690 660 199 / +237 674 316 639</span></li>
                            <li class="cv-label">Age :<span class="cv-value">&nbsp;24 ans </span></li>
                            <li class="cv-label">Adresse Email :<span class="cv-value">&nbsp;amadou_bakari@yahoo.fr</span></li>
                            <li class="cv-label">Statut :<span class="cv-value">&nbsp;Célibataire (sans enfant)</span></li>
                        </ul>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div id="formation">
                        <h2>
                            Formation D'Ingénieur
                        </h2>
                    </div>
                    <div id="experience">
                        <h2>
                            Expériences Professionnelles 
                        </h2>
                    </div>
                    <div id="competence">
                        <h2>
                            Compétences Professionnelles
                        </h2>
                    </div>
                    <div id="competence">
                        <h2>
                            Langue et outils informatiques
                        </h2>
                    </div>
                    <div id="competence">
                        <h2>
                            Centres d'Intérêt
                        </h2>
                    </div>
                </div>
                <div class="cv-footer col-xs-12">CV Amadou Bakari
                    <br><br>
                </div>
            </div>
        </div>
        <div class="col-lg-3"></div>
    </div>

    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
</body>

</html>
